<a href="https://colab.research.google.com/github/Mayur-Rahangdale245/Mayur-Rahangdale/blob/main/finding_missing_values_and_replacement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = [
    51, 66, None, 35, 94, 74, None, None, 30, 90,
    24, 68, None, None, None, None, 65, None, None, 45,
    23, None, 88, 55, None, 41, 92, None, 33, None,
    76, 29, None, 63, 84, None, None, 57, 21, None,
    72, 95, None, 46, None, 38, 67, None, 82, None,
    54, None, 27, 91, None, 43, 60, None, 78, None,
    36, 85, None, 49, None, 70, 31, None, 89, None,
    62, None, 25, 77, None, 52, None, 93, 40, None,
    69, None, 34, 81, None, 58, None, 26, 87, None,
    47, None, 73, 22, None, 64, 73, 90, 39, None,
    56, None, 83, 28, None, 71, None, 44, 86, None,
    32, None, 61, 94, None, 50, None, 79, 37, None,
    68, None, 24, 92, None, 53, None, 75, 42, None,
    88, None, 30, 66, None, 80, None, 48, 95, None,
    35, None, 59, 76, None, 23, None, 84, 45, None,
    63, None, 27, 91, None, 51, None, 70, 33, None,
    82, None, 40, 69, None, 57, None, 89, 31, None,
    74, None, 46, 85, None, 29, None, 60, 78, None,
    43, None, 93, 36, None, 67, None, 52, 81, None,
    55, None, 38, 72, None, 49, None, 87, 25, None
]

In [ ]:
df = pd.DataFrame({"Data":data})
df

     Data
0    51.0
1    66.0
2     NaN
3    35.0
4    94.0
..    ...
195  49.0
196   NaN
197  87.0
198  25.0
199   NaN

[200 rows x 1 columns]

In [ ]:
df
print("total values in data frame is",len(df))

total values in data frame is 200

In [ ]:
na=df.isna()
na
print("total null values in df is",na.sum())

total null values in df is Data    80
dtype: int64

In [ ]:
na.sum()

Data    80
dtype: int64

In [ ]:
mean=df["Data"].mean()
mean

np.float64(59.21666666666667)

In [ ]:
df["Data"]=df["Data"].fillna(mean)
print(df["Data"].isna().sum())

0

In [ ]:
df

          Data
0    51.000000
1    66.000000
2    59.216667
3    35.000000
4    94.000000
..         ...
195  49.000000
196  59.216667
197  87.000000
198  25.000000
199  59.216667

[200 rows x 1 columns]